version: '3.8'

services:
  db:
    image: postgres:14.0
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  backend:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: bash -c "
      python manage.py migrate &&
      python manage.py loaddata fixtures.json &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db