# Generated by Django 4.2.6 on 2023-10-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='Нет описания', max_length=1023, verbose_name='Описание'),
        ),
    ]
